#! /usr/bin/env bash

# ensure you run:
# `pkg install bash ffmpeg`

MEDIA_DIR="/mnt/Media/"
if [[ "$(uname -s)" == "Darwin" ]]; then
	MEDIA_DIR="/Volumes/Media/"
fi

source "${MEDIA_DIR}/Scripts/scriptlets/helpCommands"
source "${MEDIA_DIR}/Scripts/scriptlets/optionErrors"
source "${MEDIA_DIR}/Scripts/scriptlets/jsonColourParser"


display_help() {
    help_start 'seeMetadata [-h | <file name>]' 'The present script will print the metadata of a given file using `ffmpeg`.'
    help_help '2'
}


main() {
    
    /usr/local/bin/ffprobe -loglevel quiet -show_format "${1}"

}


OPTIND=1
while getopts ":-:h" OPTION; do
        case $OPTION in
                -)
                    case $OPTARG in
                        help)
                            display_help ;;
                        *)
                            opt_err ;;
                    esac ;;
                h)
                    display_help ;;
                *)
                    opt_err ;;
        esac
done


if [[ "${1}" =~ ^\-.+ ]] # checks to see if first argument begins with a minus (i.e., is an option) as we cannot assess $OPTIND before options are called
then
    :
else
    main "${1}"
fi
